### ISSUE TITLE
o1系列模型展示思考过程

### ISSUE THREAD

**Issue by SailFlorve** [Yanyutin753/xyhelperV1Api_refresh#12]
看日志，发现思考过程会触发JSON解析异常打印到日志里，希望可展示
![image](https://github.com/user-attachments/assets/80a73d80-2bf6-4673-83ee-23ec96feac71)

**Comment by Yanyutin753** [comment]
请提供完整的数据，可以考虑加上去

**Comment by SailFlorve** [comment]
backend-to-api-1  | 2024-09-26 22:19:49,031 [INFO] - 发送数据: : ping - 2024-09-26 14:19:47.812400+00:00
backend-to-api-1  | 
backend-to-api-1  | data: {"message": {"id": "f243aeec-8740-4f3e-b3ba-b98e98fc7dbb", "author": {"role": "tool", "name": "a8km123", "metadata": {}}, "create_time": null, "update_time": null, "content": {"content_type": "text", "parts": ["**Appointing aid**\n\nFirst, I greet the user, then quickly grasp the question to provide the correct answer in the user's language.\n\n**Investigating terminology**\n\nOK, I\u2019m thinking about the term 'pinnacle number' and its link to 884868. As of 2021, there's no established mathematical property for 884868 as 'pinnacle number'. It might be a new term or meme.\n\n**Reversing and converting**\n\nI'm mapping out the digits of 884868 upside down to see if they form meaningful words or phrases using calculator-style letter interpretations.\n\n**Flipping numbers**\n\nOK, let's see: flipping upside down yields BGBhB B. Considering numerology ideas and Chinese homophones is equally fascinating.\n\n**Analyzing numerical patterns**\n\nI\u2019m examining how 884868 could be linked to Mount Everest's height, possibly as a rounded version of 8848.68 meters, or more accurately, 8848.86 meters.\n\n"]}, "status": "in_progress", "end_turn": null, "weight": 0.0, "metadata": {"finished_text": "Finished thinking", "initial_text": "Thinking", "parent_id": "53d22e6f-ff01-4f38-b06f-5c0e615176c9", "model_switcher_deny": []}, "recipient": "all", "channel": null}, "conversation_id": "66f56d72-1b94-8007-85b7-b564fa4aa49b", "error": null}

**Comment by SailFlorve** [comment]
简单看了一下就是if role == "tool" and name != "python" and name != "dalle.text2im" and last_content_type != "execution_output" and content_type != None:下面直接设置new_text = ""了，针对思考场景额外判断一下并且美化下排版就好。

**Comment by Yanyutin753** [comment]
可以的 来pr🥳

**Comment by Yanyutin753** [comment]
看了一下 把代码注释掉就行 如果需要美化结构化输出的话 欢迎来pr🥳
