### ISSUE TITLE
You have sent too many messages 能否直接报错

### ISSUE THREAD

**Issue by SailFlorve** [Yanyutin753/xyhelperV1Api_refresh#4]
这样方便在one-api进行重试，否则会被判断为正常请求。。

**Comment by kuangxiaoye** [comment]
@Yanyutin753 作者大大能否看一下这个issue

**Comment by Yanyutin753** [comment]
```
upstream_response = send_text_prompt_and_get_response(messages, api_key, account_id, stream, model,
                                                       proxy_api_prefix)

```

在这个代码检测一下是否429就可以了

**Comment by Yanyutin753** [comment]
plus被封了 就没继续更新这个了，作为demo，可以自己研究一下

**Comment by kuangxiaoye** [comment]
> plus被封了 就没继续更新这个了，作为demo，可以自己研究一下

问题的确出现在这里 upstream_response ，当官方出现：

The message you submitted was too long, please reload the conversation and submit something shorter.


状态码却是200，虽然捕获了错误，却因为200状态码正常返回了数据，错误没有被抛出

ffogvmmsqp79@hotmail.com,t@seoq6gF5do

plus测试账号

**Comment by kuangxiaoye** [comment]
这里因为同步线程的问题，我没有找到很好的直接抛出错误的方法emmm

**Comment by Yanyutin753** [comment]
加我微信说吧 返回200 没显示，得看报错了

**Comment by kuangxiaoye** [comment]
好的作者大大，但是没找到你微信

在你宣传的tg群找到你tg了 你看看消息
