### ISSUE TITLE
使用普号使用GPT3.5和gpt-4o会报错you need to have a ChatGPT Plus subscription

### ISSUE THREAD

**Issue by itq5** [Yanyutin753/xyhelperV1Api_refresh#8]
使用普号使用GPT3.5和gpt-4o会报错
{"detail":"you need to have 
a ChatGPT Plus subscription"}
![image](https://github.com/Yanyutin753/RefreshToV1Api/assets/42521985/dabc870c-8828-45d6-84e2-744f17fd41e6)

**Comment by Yanyutin753** [comment]
始皇普号不支持的，换别的渠道
